name: "Draft new release"

on:
  milestone:
    types: [closed]

jobs:
  draft-new-release:
    name: "Draft a new release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          ref: 'release'
      - name: Extract version from milestone
        run: |
          VERSION="${{ github.event.milestone.title }}"
          echo "RELEASE_VERSION=${VERSION/v/}" >> $GITHUB_ENV
          # Transforms 1.13.2 to 1.13 so that we can re-use the same
          # branch for patch releases.
          echo "BRANCH_VERSION=${RELEASE_VERSION:$i:-2}" >> $GITHUB_ENV

      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@96ebf19f2bddaf72406c84691b9c2d827da53140
        with:
          version: ${{ env.RELEASE_VERSION }}

      - name: Initialize git config and commit changes
        run: |
          # Configure name and email for Actions user
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com

          # Stage and commit changes to the changelog
          git add CHANGELOG.md
          git commit -m "CHANGELOG: bump for ${RELEASE_VERSION}"

          # Increment the version as necessary. This checks if the last
          # character of the new version is 0, in which case it increments
          # the minor version, else it increments the patch version.
          if [[ "${RELEASE_VERSION: -1}" == "0" ]]; then
            ./gradlew bumpMinor
          else
            ./gradlew bumpPatch
          fi

          # Commit changes to the versioning
          git add **/version.properties
          git commit -m "build: bump version"

          # Prepare the next snapshot
          ./gradlew bumpSnapshot

          git add **/version.properties
          git commit -m "build: prepare next development version"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@45c510e1f68ba052e3cd911f661a799cfb9ba3a3
        with:
          author: GitHub Actions <noreply@github.com>
          base: release
          body: This is an automated pull request to bump the changelog for the v${{ env.RELEASE_VERSION }} release.
          branch: release-${{ env.BRANCH_VERSION }}
          title: Release v${{ env.RELEASE_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
