on: [pull_request]

name: Check pull request
jobs:
  test-pr:
    runs-on: ubuntu-latest
    steps:

    #- name: Auto-cancel redundant workflow run
    #  uses: technote-space/auto-cancel-redundant-workflow@f9dfa1c127a520e4d71b92892850f861fb861206

    - name: Check if relevant files have changed
      uses: actions/github-script@a3e7071a34d7e1f219a8a4de9a5e0a34d1ee1293
      id: service-changed
      with:
        result-encoding: string
        script: |
          const result = await github.pulls.listFiles({
            owner: context.payload.repository.owner.login,
            repo: context.payload.repository.name,
            pull_number: context.payload.number,
            per_page: 100
          })
          const files = result.data.filter(file =>
            // We wanna run this if the PR workflow is modified
            (file.filename.endsWith("yml") && file.filename.endsWith("pull_request.yml")) ||
            // Changes in Markdown files don't need tests
            file.filename.endsWith("md") ||
            // Changes to fastlane metadata aren't covered by tests
            file.filename.startsWith("fastlane/")
          )
          console.log(files)
          // If filtered file count and source file count is equal, it means all files
          // in this PR are skip-worthy.
          return files.length == result.data.length
